"""Source-constrained HUNL value-network training adapter.

Primary DeepStack evidence fixes this computational graph:
  card ranges -> 1000 bucket distributions -> 7x500 PReLU network
  -> 1000 bucket CFVs/player -> zero-sum correction -> inverse bucketing
  -> card counterfactual values (1326/player).

The private HUNL code did not reveal how card-level solved training targets were
reduced to bucket-space targets.  We therefore avoid inventing that reduction:
training loss is evaluated after inverse bucketing in card space, against the
actual per-hand CFVs generated by the exact-to-end turn solver.

This is SOURCE-CONSISTENT_RECONSTRUCTION, not a claim about the unpublished
loss implementation used in the private 2016 HUNL trainer.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Sequence

import numpy as np
import torch
from torch import Tensor
import torch.nn.functional as F

from .cards import HAND_COUNT, possible_hands_mask
from .value_bucketing import BoardBucketMap, BucketProvider, POSTFLOP_BUCKET_COUNT
from .value_network import DeepStackHUNLValueNet


@dataclass(frozen=True)
class PreparedValueBatch:
    inputs: Tensor                 # [B,2001]
    card_targets: Tensor           # [B,2,1326]
    legal_mask: Tensor             # [B,1326] bool
    maps: tuple[BoardBucketMap, ...]


def prepare_turn_training_batch(
    *,
    boards: Sequence[Sequence[int]],
    ranges: np.ndarray,            # [B,2,1326]
    pot_halves: np.ndarray,        # [B], per-player committed amount
    card_targets: np.ndarray,      # [B,2,1326], fraction-of-pot targets
    bucket_provider: BucketProvider,
    stack: int = 20000,
    dtype: torch.dtype = torch.float32,
) -> PreparedValueBatch:
    r = np.asarray(ranges, dtype=np.float32)
    t = np.asarray(card_targets, dtype=np.float32)
    p = np.asarray(pot_halves, dtype=np.float32).reshape(-1)
    b = len(boards)
    if r.shape != (b,2,HAND_COUNT):
        raise ValueError(f"ranges must be [{b},2,{HAND_COUNT}], got {r.shape}")
    if t.shape != (b,2,HAND_COUNT):
        raise ValueError(f"card_targets must be [{b},2,{HAND_COUNT}], got {t.shape}")
    if p.shape != (b,):
        raise ValueError(f"pot_halves must be [{b}], got {p.shape}")
    x = np.zeros((b, 2*POSTFLOP_BUCKET_COUNT+1), dtype=np.float32)
    legal_masks = np.zeros((b,HAND_COUNT), dtype=bool)
    maps=[]
    for i,board0 in enumerate(boards):
        board=tuple(int(c) for c in board0)
        if len(board)!=4:
            raise ValueError("turn training requires 4-card public boards")
        bm=bucket_provider.for_board(board)
        maps.append(bm)
        legal=bm.legal_mask
        legal_masks[i]=legal
        # Inputs are distributions over buckets.  Data-generator ranges are
        # normalized in legal card space; tolerate tiny f32 drift only.
        for pl in range(2):
            br=bm.range_to_buckets(r[i,pl])
            mass=float(br.sum(dtype=np.float64))
            if not np.isfinite(mass) or mass<=0:
                raise ValueError("range has no legal mass")
            br=(br/np.float32(mass)).astype(np.float32)
            x[i,pl*1000:(pl+1)*1000]=br
        x[i,-1]=np.float32(p[i]/np.float32(stack))
    return PreparedValueBatch(
        inputs=torch.as_tensor(x,dtype=dtype),
        card_targets=torch.as_tensor(t,dtype=dtype),
        legal_mask=torch.as_tensor(legal_masks,dtype=torch.bool),
        maps=tuple(maps),
    )


def prepare_river_training_batch(
    *,
    boards: Sequence[Sequence[int]],
    ranges: np.ndarray,            # [B,2,1326]
    pot_halves: np.ndarray,        # [B], per-player committed amount
    targets_chips: np.ndarray,     # [B,2,1326], raw solver CFVs in chips
    bucket_provider: BucketProvider,
    stack: int = 20000,
    dtype: torch.dtype = torch.float32,
) -> PreparedValueBatch:
    """River branch of the same graph, on 5-card boards.

    Supremus states the pot feature as current pot over starting chips and the
    outputs as a fraction of current pot size.  Both are read literally against
    the *total* pot, i.e. twice the per-player committed amount:

        pot_feature = 2*pot_half / stack
        target      = raw_chip_CFV / (2*pot_half)

    Raw chip targets stay the primary saved artifact; normalization happens
    here so that a later change of bucketing never forces the expensive
    4,000-iteration solves to be repeated.
    """
    r = np.asarray(ranges, dtype=np.float32)
    tc = np.asarray(targets_chips, dtype=np.float64)
    p = np.asarray(pot_halves, dtype=np.float64).reshape(-1)
    b = len(boards)
    if r.shape != (b,2,HAND_COUNT):
        raise ValueError(f"ranges must be [{b},2,{HAND_COUNT}], got {r.shape}")
    if tc.shape != (b,2,HAND_COUNT):
        raise ValueError(f"targets_chips must be [{b},2,{HAND_COUNT}], got {tc.shape}")
    if p.shape != (b,):
        raise ValueError(f"pot_halves must be [{b}], got {p.shape}")
    if not np.all(p > 0):
        raise ValueError("pot_half must be positive to normalize by total pot")
    x = np.zeros((b, 2*POSTFLOP_BUCKET_COUNT+1), dtype=np.float32)
    t = np.zeros((b,2,HAND_COUNT), dtype=np.float32)
    legal_masks = np.zeros((b,HAND_COUNT), dtype=bool)
    maps=[]
    for i,board0 in enumerate(boards):
        board=tuple(int(c) for c in board0)
        if len(board)!=5:
            raise ValueError("river training requires 5-card public boards")
        bm=bucket_provider.for_board(board)
        maps.append(bm)
        legal=bm.legal_mask
        legal_masks[i]=legal
        for pl in range(2):
            br=bm.range_to_buckets(r[i,pl])
            mass=float(br.sum(dtype=np.float64))
            if not np.isfinite(mass) or mass<=0:
                raise ValueError("range has no legal mass")
            x[i,pl*1000:(pl+1)*1000]=(br/np.float32(mass)).astype(np.float32)
        total_pot=2.0*float(p[i])
        x[i,-1]=np.float32(total_pot/float(stack))
        t[i]=(tc[i]/total_pot).astype(np.float32)
    return PreparedValueBatch(
        inputs=torch.as_tensor(x,dtype=dtype),
        card_targets=torch.as_tensor(t,dtype=dtype),
        legal_mask=torch.as_tensor(legal_masks,dtype=torch.bool),
        maps=tuple(maps),
    )


def inverse_bucket_outputs(bucket_outputs: Tensor, maps: Sequence[BoardBucketMap]) -> Tensor:
    """Differentiable bucket->card scatter matching Figure 3 semantics."""
    if bucket_outputs.ndim!=2 or bucket_outputs.shape[1]!=2000:
        raise ValueError("bucket_outputs must be [B,2000]")
    if len(maps)!=bucket_outputs.shape[0]:
        raise ValueError("one BoardBucketMap required per batch row")
    rows=[]
    device=bucket_outputs.device
    for i,bm in enumerate(maps):
        ids=torch.as_tensor(bm.hand_to_bucket.astype(np.int64),device=device)
        legal=ids>=0
        per=[]
        for pl in range(2):
            bv=bucket_outputs[i,pl*1000:(pl+1)*1000]
            hv=torch.zeros(HAND_COUNT,dtype=bucket_outputs.dtype,device=device)
            hv[legal]=bv[ids[legal]]
            per.append(hv)
        rows.append(torch.stack(per,dim=0))
    return torch.stack(rows,dim=0)


def masked_card_huber_loss(card_outputs: Tensor, card_targets: Tensor, legal_mask: Tensor) -> Tensor:
    """Mean Smooth-L1/Huber over both players and legal private hands only."""
    if card_outputs.shape!=card_targets.shape or card_outputs.ndim!=3 or card_outputs.shape[1:]!=(2,HAND_COUNT):
        raise ValueError("card outputs/targets must both be [B,2,1326]")
    if legal_mask.shape!=(card_outputs.shape[0],HAND_COUNT):
        raise ValueError("legal_mask must be [B,1326]")
    mask=legal_mask[:,None,:].expand_as(card_outputs)
    return F.smooth_l1_loss(card_outputs[mask],card_targets[mask],reduction='mean',beta=1.0)


def forward_card_values(model: DeepStackHUNLValueNet, batch: PreparedValueBatch) -> Tensor:
    bucket_outputs=model(batch.inputs)
    return inverse_bucket_outputs(bucket_outputs,batch.maps)


def loss_on_prepared_batch(model: DeepStackHUNLValueNet, batch: PreparedValueBatch) -> Tensor:
    return masked_card_huber_loss(forward_card_values(model,batch),batch.card_targets,batch.legal_mask)

def train_smoke_steps(
    model: DeepStackHUNLValueNet,
    batch: PreparedValueBatch,
    *,
    steps: int = 40,
    learning_rate: float = 1e-3,
) -> list[float]:
    """Adam descent on one fixed batch, for wiring checks only.

    This exists to prove the graph is differentiable end to end and that the
    zero-sum outer layer survives optimization.  Driving the loss down on a
    handful of subgames is deliberate overfitting and is never evidence about
    model quality: Supremus trained on 50 million river subgames.
    """
    opt = torch.optim.Adam(model.parameters(), lr=float(learning_rate))
    losses: list[float] = []
    model.train()
    for _ in range(int(steps)):
        opt.zero_grad(set_to_none=True)
        loss = loss_on_prepared_batch(model, batch)
        loss.backward()
        opt.step()
        losses.append(float(loss.detach()))
    return losses


__all__=[
    'PreparedValueBatch','prepare_turn_training_batch','prepare_river_training_batch',
    'inverse_bucket_outputs','masked_card_huber_loss','forward_card_values',
    'loss_on_prepared_batch','train_smoke_steps'
]
